from .genre_selection import render_genre_selection
from .movie_input import render_movie_input
from .movie_recommendations import display_movie_cards, render_popular_movies, render_recommended_movies, custom_card
